name: Python CI-CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Unit Tests
        # Yahan humne direct file ko trigger kiya hai
        run: python test_app.py

      - name: Run Security Scan (DevSecOps)
        # B101 (assert) ko skip kiya hai taaki testing mein fail na ho
        run: bandit -r . -skip B101