name: Python CI-CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: pip install bandit
      - name: Run Unit Tests
        run: python test_app.py
      - name: Run Security Scan (DevSecOps)
        run: bandit -r . -s B101